all:
	mkdir -p mountdir
	mkdir -p rootdir
	echo "bogus file \n" > rootdir/bogus.txt
	echo "are you sure you want this \n are you sure you want this \n are you sure you want this \n are you sure you want this \n are you sure you want this \n are you sure you want this \n are you sure you want this \n are you sure you want this \n are you sure you want this \n are you sure you want this \n are you sure you want this \n are you sure you want this \n are you sure you want this \n are you sure you want this \n are you sure you want this \n are you sure you want this \n are you sure you want this \n are you sure you want this \n are you sure you want this \n are you sure you want this \n are you sure you want this \n are you sure you want this \n are you sure you want this \n are you sure you want this \n are you sure you want this \n are you sure you want this \n are you sure you want this \n are you sure you want this \n are you sure you want this \n" > rootdir/lol.txt

distdir:
	cp Makefile $(distdir)

mostlyclean clean distclean mainainer-clean:
	rm -r mountdir rootdir
